[build]
  # Build command for Vite
  command = "npm run build"
  # Directory to publish
  publish = "dist"

[build.environment]
  # Set Node.js version for builds and functions
  NODE_VERSION = "22"

# Environment variables for functions
[functions]
  # Environment variables for Netlify Functions
  OPENAI_API_KEY = "your-openai-api-key-here"

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle SPA routing - redirect all non-API requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
